name: Update predicted table

on:
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:
concurrency:
  group: scraper
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install

      - name: Run scraper
        run: python scraper.py

      - name: Commit updated CSV
        run: |
          
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git pull --rebase origin main
          git add predicted_table.csv
          git commit -m "update predicted table" || exit 0
          git push origin main
