name: Scrape and Update Sheet

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run scraper
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: python optascraper.py
